name: Example Workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variable
        if: ${{ github.ref == 'refs/heads/master' }}
        run: echo "MY_VAR=example" >> $GITHUB_ENV

      - name: Use Environment Variable
        run: |
          echo "Value of MY_VAR is $MY_VAR"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Use Environment Variable
        run: |
          echo "Value of MY_VAR from previous job is ${{ needs.build.outputs.MY_VAR }}"
    
      # This step is only executed if MY_VAR is "example"
      - name: Deploy App
        if: ${{ needs.build.outputs.my_var == 'example' }}
        run: |
          echo "Deploying app..."
