name: My Git Action
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set ENV Variable
        run: echo "action_state=yellow" >> $GITHUB_ENV
          
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print ENV Variable
        run: echo "${{ env.action_state }}"
